spring.application.name=CB_management
# ============================================
# SERVER CONFIGURATION
# ============================================
server.port=9091

# ============================================
# POSTGRESQL DATABASE CONFIGURATION
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/bc_management
spring.datasource.username=postgres
spring.datasource.password=hadil123
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / HIBERNATE CONFIGURATION
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# JWT CONFIGURATION
# ============================================
jwt.secret=MaCleSecreteSuperLongueEtSecurisee2025PourLeProjetCBManagementPFE123456789
jwt.expiration=86400000

# ============================================
# SWAGGER / OPENAPI CONFIGURATION
# ============================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method

# ============================================
# JACKSON DATE CONFIGURATION
# ============================================
# Use serialization property only in Spring Boot 3/4 with Jackson 3
# spring.jackson.serialization.write-dates-as-timestamps=false

# spring.jackson.deserialization.READ_DATES_AS_TIMESTAMPS=true
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# Compte admin par defaut
app.admin.email=admin@alghanja.tn
app.admin.password=Admin@2025
app.admin.nom=Administrateur
app.admin.prenom=Al-Ghanja